export const featuredJobs = [
  {
    id: "job1",
    title: "Senior Frontend Developer",
    company: "TechCorp Inc.",
    logo: "/placeholder.svg?height=40&width=40",
    location: "San Francisco, CA (Remote)",
    salary: "$120,000 - $150,000",
    type: "Full-time",
    tags: ["React", "TypeScript", "Next.js"],
    postedAt: "2 days ago",
    aiMatch: true,
    matchPercentage: 95,
    isSaved: false,
    isApplied: false,
  },
  {
    id: "job2",
    title: "Full Stack Developer",
    company: "InnovateSoft",
    logo: "/placeholder.svg?height=40&width=40",
    location: "New York, NY (Hybrid)",
    salary: "$115,000 - $145,000",
    type: "Full-time",
    tags: ["Node.js", "React", "MongoDB"],
    postedAt: "1 week ago",
    aiMatch: true,
    matchPercentage: 92,
    isSaved: false,
    isApplied: false,
  },
  {
    id: "job3",
    title: "UX Designer",
    company: "DesignHub",
    logo: "/placeholder.svg?height=40&width=40",
    location: "Austin, TX (Remote)",
    salary: "$90,000 - $120,000",
    type: "Full-time",
    tags: ["Figma", "UI Design", "User Research"],
    postedAt: "3 days ago",
    aiMatch: false,
    matchPercentage: 78,
    isSaved: false,
    isApplied: false,
  },
  {
    id: "job4",
    title: "Product Manager",
    company: "ProductWave",
    logo: "/placeholder.svg?height=40&width=40",
    location: "Seattle, WA (On-site)",
    salary: "$130,000 - $160,000",
    type: "Full-time",
    tags: ["Product Strategy", "Agile", "B2B"],
    postedAt: "5 days ago",
    aiMatch: true,
    matchPercentage: 88,
    isSaved: false,
    isApplied: false,
  },
  {
    id: "job5",
    title: "DevOps Engineer",
    company: "CloudTech",
    logo: "/placeholder.svg?height=40&width=40",
    location: "Remote",
    salary: "$125,000 - $155,000",
    type: "Full-time",
    tags: ["AWS", "Kubernetes", "CI/CD"],
    postedAt: "1 week ago",
    aiMatch: false,
    matchPercentage: 82,
    isSaved: false,
    isApplied: false,
  },
  {
    id: "job6",
    title: "Data Scientist",
    company: "DataInsights",
    logo: "/placeholder.svg?height=40&width=40",
    location: "Boston, MA (Hybrid)",
    salary: "$110,000 - $140,000",
    type: "Full-time",
    tags: ["Python", "Machine Learning", "SQL"],
    postedAt: "2 weeks ago",
    aiMatch: true,
    matchPercentage: 90,
    isSaved: false,
    isApplied: false,
  },
  {
    id: "job7",
    title: "Mobile Developer (iOS)",
    company: "AppWorks",
    logo: "/placeholder.svg?height=40&width=40",
    location: "Chicago, IL (Remote)",
    salary: "$100,000 - $130,000",
    type: "Full-time",
    tags: ["Swift", "iOS", "Mobile"],
    postedAt: "3 days ago",
    aiMatch: false,
    matchPercentage: 75,
    isSaved: false,
    isApplied: false,
  },
  {
    id: "job8",
    title: "Backend Engineer",
    company: "ServerStack",
    logo: "/placeholder.svg?height=40&width=40",
    location: "Remote",
    salary: "$115,000 - $145,000",
    type: "Full-time",
    tags: ["Java", "Spring Boot", "Microservices"],
    postedAt: "1 week ago",
    aiMatch: true,
    matchPercentage: 85,
    isSaved: false,
    isApplied: false,
  },
]

export const trendingSkills = [
  { name: "React", growth: 35, demand: 95 },
  { name: "TypeScript", growth: 42, demand: 92 },
  { name: "Next.js", growth: 55, demand: 88 },
  { name: "AI/ML", growth: 65, demand: 90 },
  { name: "Cloud (AWS/Azure)", growth: 38, demand: 94 },
  { name: "DevOps", growth: 30, demand: 89 },
  { name: "Cybersecurity", growth: 45, demand: 93 },
  { name: "Data Science", growth: 40, demand: 91 },
]

